### ISSUE TITLE
Hydrogen alternative

### ISSUE THREAD

**Issue by slavaGanzin** [t9md/atom-try#3]
Hello @t9md 

I found this package and I think you should try this, it works not only with coffeescript:
https://github.com/nteract/hydrogen maybe it would be helpful for you.

If you need any help just ask

p.s. Thanks for all your packages - use 'em a lot

**Comment by t9md** [comment]
This is just a package to copy selected text to pre-specified filePath.
It's like scratch pad.
Not code eval package like hydrogen or script.
Maybe you misunderstood because in GIF I run code via script package.
This is for just demonstrate workflow like select text then copy specified filePath then execute code via script.
